# 기본적인 이미지 처리 기술을 이용한 이미지 선명하게 해보기

선명화 프로세스는 일반적으로 이미지의 가장자리를 향상시키는 데 사용됩니다. 우리가 사용할 수 있
는 많은 필터가 있지만 이미지를 선명하게 할 수 있는 필터는 아래 매트릭스에 표시되어 있습니다

[-1 -1 -1] 

[-1  9 -1]

[-1 -1 -1]

보시다시피 이 필터는 중앙에 양수 9가 있는 반면 다른 모든 위치에는 -1이 있습니다. 이 특정 필터의 경
우 구현된 OpenCV 기능이 없습니다.

따라서 cv2.filter2D() 임의의 필터로 이미지를 처리하는 기능을 사용할 것입니다. 이 필터는 종종 컬러
이미지를 선명하게 하는데 사용됩니다. 

In [1]:
import cv2
import numpy as np
from utils import image_show

In [2]:
image = cv2.imread('./car.jpg')

In [3]:
# Creating out sharpening filter
filter = np.array([[-1, -1, -1], [-1, 9, -1], [-1, -1, -1]])

In [5]:
sharpen_img = cv2.filter2D(image, -1, filter)
cv2.imshow("org image ", image)
cv2.waitKey(0)
image_show(sharpen_img)
cv2.imwrite("03.Shaper.png",sharpen_img)

True