In [1]:
import cv2
import numpy as np

# Python에서 OpenCV로 얼굴정렬

- 얼굴 및 눈 감지를 위해 OpenCV Haar 캐스케이드 구성을 사용해야함

In [2]:
# Creating face_cascade and eye_cascade objects
face_cascade = cv2.CascadeClassifier("haarcascade_frontalface_default.xml") # 감지된 얼굴
eye_cascade = cv2.CascadeClassifier("haarcascade_eye.xml") # 감지된 눈

In [3]:
# Loading the image ..
img = cv2.imread("./face.png")
cv2.imshow("image show", img)
cv2.waitKey(0)

-1

얼굴 이미지 바운딩 박스 >> 케스케이드 경우에는 그레이 스케일 이미지에서만 작동

그래서 cvtColor을 통해 컬러이미지 >> 흑백 으로 재구성 해줘야함

In [4]:
# Converting the image into grayscale
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

In [5]:
faces = face_cascade.detectMultiScale(gray, 1.1, 4)
faces

array([[ 45,  52, 219, 219]])

In [6]:
# Defining and drawing the rectangles around the face
for (x, y, w, h) in faces:
    cv2.rectangle(img, (x, y), (x+w, y+h), (255, 0, 255), 2)

roi_gray => 눈을 감지할 회색조 이미지 첫번째 영역이 필요함

roi_color => 얼굴 전ㄴ체 사각형을 그릴 컬러 이미지가 필요

In [7]:
roi_gray = gray[y:(y+h), x:(x+w)]
roi_color = img[y:(y+h), x:(x+w)]

In [8]:
# eyes
eyes = eye_cascade.detectMultiScale(roi_gray, 1.1, 4)
print(eyes)
index = 0

[[ 41  82  45  45]
 [112  48  52  52]]


In [9]:
# Creating for loop in order to divide one eye from another
for (ex, ey, ew, eh) in eyes:
    if index == 0:
        eye_1 = (ex, ey, ew, eh)
    elif index == 1:
        eye_2 = (ex, ey, ew, eh)

    cv2.rectangle(roi_color, (ex, ey), (ex+ew, ey+eh), (0, 0, 255), 2)
    index = index + 1

In [10]:
cv2.imshow("face", img)
cv2.waitKey(0)


-1

# 개인 사진으로 한번 더 해보기!! 

In [11]:
# Loading new image ..
img = cv2.imread("./viv.jpg")
cv2.imshow("my image", img)
cv2.waitKey(0)

-1

In [12]:
# Repeat the steps above

gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

faces = face_cascade.detectMultiScale(gray, 1.1, 4)
for (x, y, w, h) in faces:
    cv2.rectangle(img, (x, y), (x+w, y+h), (255, 0, 255), 2)


roi_gray = gray[y:(y+h), x:(x+w)]
roi_color = img[y:(y+h), x:(x+w)]

# eyes
eyes = eye_cascade.detectMultiScale(roi_gray, 1.1, 4)
print(eyes)
"""
[[ 41  82  45  45]
 [112  48  52  52]]
"""
index = 0

# Creating for loop in order to divide one eye from another
for (ex, ey, ew, eh) in eyes:
    if index == 0:
        eye_1 = (ex, ey, ew, eh)
    elif index == 1:
        eye_2 = (ex, ey, ew, eh)

    cv2.rectangle(roi_color, (ex, ey), (ex+ew, ey+eh), (0, 0, 255), 2)
    index = index + 1

cv2.imshow("face", img)
cv2.waitKey(0)


()


-1

눈은 잘 찾아 내었으나, 마스크와 머리를 덮은 후드때문에 얼굴인식은 잘 안된 것으로 보임...