### Tensor 사용법

- 텐서는 배열(array)나 행렬(matrix)과 매우 유사함

- PyTorch에서는 텐서를 사용하여 모델의 입출력 + 모델의 매개변수를 부호화(encode)시켜줌

- 텐서는 GPU나 다른 연산 가속을 위한 특수한 하드웨어에서 실행가능

- Numpy의 ndarray와 매우 유사함

In [2]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

### 텐서 초기화하기

- 데이터로부터 직접 텐서를 생성 가능
- 데이터의 자료형은 자동으로 유추함





In [3]:
data = [[1,2],[3,4]]
x_data = torch.tensor(data)
x_data

tensor([[1, 2],
        [3, 4]])

### Numpy 배열로 부터 탠서 생성

- Numpy와 기본 배열 생성 후 torch.from_numpy를 통해 tensor로 변경

In [4]:
np_array = np.array(data)
print("numpy type: ",type(np_array))
x_np = torch.from_numpy(np_array)
print("Numpy -> torch: ",type(x_np))
x_np.shape

numpy type:  <class 'numpy.ndarray'>
Numpy -> torch:  <class 'torch.Tensor'>


torch.Size([2, 2])

### tensor로 바뀐 데이터를 DataFrame으로 변경

In [5]:
dp = pd.DataFrame(x_data)
dp

0  1
0  1  2
1  3  4

### 다른 텐서로부터 생성하기

- 명시적으로 재정의(override)하지 않는다면, 인자로 주어진 텐서의 속성(모양(shape)), 자료형(datatype)을 유지

In [6]:
x_ones = torch.ones_like(x_data) # x_data의 속성을 유지
print(f"Ones Tensor >>\n", x_ones, '\n')

Ones Tensor >>
 tensor([[1, 1],
        [1, 1]]) 



In [7]:
x_rand = torch.rand_like(x_data, dtype= torch.float)# x_data의 속성을 덮어씁니다.
print(x_rand, '\n')

tensor([[0.8696, 0.7609],
        [0.4650, 0.5283]]) 



### 무작위(random) 또는 상수(constant) 값을 사용하기

- shape은 텐서의 차원(dimention)을 나타내는 튜플(tuple)타입으로, 아래 tensor들의 차원을 결정해줌

In [8]:
shape = (3, 3) # shape 을 먼저 정해줌
randn_tensor = torch.rand(shape)
ones_tensor  = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor >>\n", randn_tensor, '\n')
print(f"Ones Tensor >>\n"  , ones_tensor , '\n')
print(f"Zeros Tensor >>\n" , zeros_tensor, '\n')

Random Tensor >>
 tensor([[0.4653, 0.4375, 0.0548],
        [0.8847, 0.8322, 0.8290],
        [0.0489, 0.6955, 0.2814]]) 

Ones Tensor >>
 tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor >>
 tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]) 



### 텐서의 속성(Attribute)

- 텐서의 속성은 텐서의 모양(shape), 자료형(datatype) 및 어느 장치에 저장되는지를 나타냄


In [9]:
tensor = torch.rand(3, 4) # shape을 직접 대입
print(f"Shape of tensor: {tensor.shape}") # 모양
print(f"Data type of tensor: {tensor.dtype}") # 타입
print(f"Device tensor is stored on : {tensor.device}", '\n') # 작동되는 하드웨어의 종류
print(f"Random Tensor >>", tensor, '\n')

Shape of tensor: torch.Size([3, 4])
Data type of tensor: torch.float32
Device tensor is stored on : cpu 

Random Tensor >> tensor([[0.2807, 0.8896, 0.7847, 0.1606],
        [0.4159, 0.7166, 0.3224, 0.0517],
        [0.5245, 0.8586, 0.6713, 0.8875]]) 



### 텐서 연산(Operation)

- 전치(transposing),인덱싱(indexing),슬라이싱(slicing),수학 계산,선형 대수,임의 샘플링(random sampling)등,100가지 이상의 텐서 연산들을 알려주는 링크
    - https://pytorch.org/docs/stable/torch.html 


- 각 연산들은 (일반적으로 CPU보다 빠른)GPU에서 실행할 수 있습니다.

- 아래는 GPU가 존재하면 텐서를 이동시키는 조건문

In [10]:
if torch.cuda.is_available():
    tensor = tensor.to('cuda')
else:
    tensor = tensor.to('cpu')
print("Device tensor is stored on : ", tensor.device)

Device tensor is stored on :  cpu


### tensor을 사용한 Numpy 식의 표준 인덱싱과 슬라이싱

In [11]:
tensor  = torch.ones((4,4))
tensor[: , 1] = 3
print(tensor)

tensor([[1., 3., 1., 1.],
        [1., 3., 1., 1.],
        [1., 3., 1., 1.],
        [1., 3., 1., 1.]])


### 텐서 합치기 및 곱하기

- 텐서를 합치기 위해 torch.cat()을 사용

- 텐서의 곱은
    - *을 사용해 요소별 곱을 계산
    - @을 사용해 행렬 곱(matrix multiplication)을 계산

In [12]:
data = [[1,2],[3,4]]
tensor  = torch.tensor(data)
t1 = torch.cat([tensor, tensor], dim = 1)
t2 = tensor * tensor
t3 = tensor @ tensor

print("Tensor Original:\n",tensor,"\n")
print("tensor 합치기:\n",t1, '\n')
print("tensor 곱하기(각 자리별):\n",t2, '\n')
print("tensor 곱하기(각 행렬별):\n",t3)

Tensor Original:
 tensor([[1, 2],
        [3, 4]]) 

tensor 합치기:
 tensor([[1, 2, 1, 2],
        [3, 4, 3, 4]]) 

tensor 곱하기(각 자리별):
 tensor([[ 1,  4],
        [ 9, 16]]) 

tensor 곱하기(각 행렬별):
 tensor([[ 7, 10],
        [15, 22]])


### tensor 바꿔치기 (in_place)

- 연산 _접미사를 갖는 연산들은 바꿔치기(in-place) 연산입니다.

- 예를 들어 x.copy()나 x.t_()는 x변경합니다.

- 바꿔치기 연산은 메모리를 일부 절약하지만,기록(history)이 즉시 삭제되어 도함수(derivative)계산에 문제가 발생할 수 있습니다.
    - *** 따라서,사용을 권장하지 않습니다. ***

In [13]:
t  = torch.ones(5)
t.add_(5)
print(t)

tensor([6., 6., 6., 6., 6.])


### Numpy 변환 (Bridge)

- CPU 상의 텐서와 Numpy 배열은 메모리 공간을 공유하기 때문에, 하나를 변경하면 다른 하나도 변경됨

In [14]:
# 텐서의 변경사항이 Numpy에 적용됨
n = np.ones(5)
print("Original: ",n)
t = torch.from_numpy(n)
t.add_(3)
v= t.add(2)
print("From numpy, add_(3): ",t)
print("Original After: ",n)
print("From above, add(2): ",v)
print("Original After: ",n)

Original:  [1. 1. 1. 1. 1.]
From numpy, add_(3):  tensor([4., 4., 4., 4., 4.], dtype=torch.float64)
Original After:  [4. 4. 4. 4. 4.]
From above, add(2):  tensor([6., 6., 6., 6., 6.], dtype=torch.float64)
Original After:  [4. 4. 4. 4. 4.]


In [15]:
# Numpy의 변경사항이 텐서에 적용됨
n = np.ones(5)
t = torch.from_numpy(n)
np.add(n, 1, out = n)
print(n)
print(t)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


### ***중요*** View

- View(뷰) - 원소의 수를 유지하면서 텐서의 크기 변경

- 넘파이에서의 리쉐이프(Reshape)와 같은 역할을 함

- 텐서의 크기를 변경해주는 역할

In [16]:
# view
t = np.array( [[[0,1,2], [3,4,5]], [[6,7,8], [9,10,11]]] )
ft = torch.FloatTensor(t)
print(ft.shape)
print(ft)

torch.Size([2, 2, 3])
tensor([[[ 0.,  1.,  2.],
         [ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.],
         [ 9., 10., 11.]]])


### View를 사용해서 3차원 -> 2차원

- view([-1, 3])이 가지는 의미는 이와 같습니다. 
1. -1은 첫번째 차원은 사용자가 잘 모르겠으니 파이토치에 맡기겠다는 의미 
2. 3은 두번째 차원의 길이는 3을 가지도록 하라는 의미입니다. 다시 말해 현재 3차원 텐서를 2차원 텐서로 변경하되 (?, 3)의 크기로 변경하라는 의미입니다. 
- 결과적으로 (4, 3)의 크기를 가지는 텐서를 얻었습니다.
- 내부적으로 크기 변환은 다음과 같이 이루어졌습니다. (2, 2, 3) -> (2 × 2, 3) -> (4, 3)

In [17]:
# 3차원 텐서-> 2차원 변경
print("Original: \n",ft)
print("Original Shape: ", ft.shape)

new_tensor = ft.view([-1,3]) #ft라는 텐서를(?,3)의 크기로 변경

print("\nReshaped: \n", new_tensor)
print("Reshaped Shape: ", new_tensor.shape)

Original: 
 tensor([[[ 0.,  1.,  2.],
         [ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.],
         [ 9., 10., 11.]]])
Original Shape:  torch.Size([2, 2, 3])

Reshaped: 
 tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
Reshaped Shape:  torch.Size([4, 3])


### Tensor 규칙 정리

- view는 기본적으로 변경 전과 변경 후의 텐서 안의 원소의 개수가 유지되어야 합니다.

- 파이토치의 view는 사이즈가 -1로 설정되면 다른 차원으로부터 해당 값을 유추합니다.

- 변경 전 텐서의 원소의 수는 (2 × 2 × 3) = 12개 -> 변경 후 텐서의 원소의 개수 또한 (4 × 3) = 12개

### 3차원 텐서의 크기 변경

- 이번에는 3차원 텐서에서 3차원 텐서로 차원은 유지하되, 크기(shape)를 바꾸는 작업을 해보겠습니다. 

- view로 텐서의 크기를 변경하더라도 원소의 수는 유지되어야 한다고 언급한 바 있습니다.

- 그렇다면 (2 × 2 × 3) 텐서를 (? × 1 × 3) 텐서로 변경하라고 하면 ?는 몇 차원인가요?
    - (2 × 2 × 3) = (? × 1 × 3) = 12를 만족해야 하므로 ?는 4가 됩니다. 이를 실습으로 확인해봅시다.

In [18]:
t = np.array( [[[0,1,2], [3,4,5]], [[6,7,8], [9,10,11]]] )
ft = torch.FloatTensor(t)
print(ft.view([-1, 1, 3]))
print(ft.view([-1, 1, 3]).shape)

tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])
torch.Size([4, 1, 3])


### ft.squeeze() 스퀴즈 - 1차원 제거

- 스퀴즈는 차원이 1인 경우에는 해당 차원을 제거합니다. 실습을 위해 임의로 (3 × 1)의 크기를 가지는 2차원 텐서를 만들겠습니다.

In [22]:
# 3 x 1
ft = torch.FloatTensor([[0], [1], [2]])
print(ft)
print(ft.shape)

# 스퀴즈 : 1인 차원 제거
print(ft.squeeze())
print(ft.squeeze().shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])
tensor([0., 1., 2.])
torch.Size([3])


### ft.Unsqueeze 언스퀴즈 - 특정 위치에 1인 차원을 추가

In [21]:
# 언스퀴즈
print(ft.unsqueeze(0))
print(ft.unsqueeze(0).shape)

tensor([[[0.],
         [1.],
         [2.]]])
torch.Size([1, 3, 1])
